### ISSUE TITLE
Recognizing printed and handwritten text

### ISSUE THREAD

**Issue by sandrapavankumar** [Azure-Samples/cognitive-services-vision-csharp-sdk-quickstarts#2]
For Recognizing printed and handwritten characters please update docs with the code.

**Comment by easyj2j** [comment]
[Quickstart: Extract handwritten text using the Computer Vision SDK and C#](https://docs.microsoft.com/en-us/azure/cognitive-services/Computer-vision/quickstarts-sdk/csharp-hand-text-sdk)

Printed text can be recognized using the same example by changing `TextRecognitionMode.Handwritten` to `TextRecognitionMode.Printed`. Will add a note to the current doc.

**Comment by easyj2j** [comment]
Above linked quickstart now has instructions to recognize handwritten or printed text.
