### ISSUE TITLE
GenerateThumbnail.sln

### ISSUE THREAD

**Issue by v-jush** [Azure-Samples/cognitive-services-vision-csharp-sdk-quickstarts#4]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
run GenerateThumbnail.sln
### Any log messages given by the failure
>
Images being analyzed ...

Thumbnail NOT written to: C:\Users\v-jush\source\repos\Text_thumb.PNG

Thumbnail NOT written to: C:\Users\v-jush\source\repos\Cognitive services\GitHub\ComputerVision\GenerateThumbnail\bin\Debug\Bloodhound_Puppy_thumb.jpg

Press ENTER to exit

### Expected/desired behavior
>
Get  Text_thumb.PNG and Bloodhound_Puppy_thumb.jpg
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Win10 
### Versions
>
18290
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by wiazur** [comment]
Updated sample.
